### ISSUE TITLE
Wiggler source size calculation

### ISSUE THREAD

**Issue by zimeng657** [oasys-kit/shadow3#40]
Hello,

I have a problem when tracing a wiggler source using shadowoui. The sizes of source it gives are different from that of Spectra with the same parameters. It gives 118 micron x 35 micron with two distinct spots as shown below while the Spectra gives 1940 micron x 160 micron.  

![wiggler](https://user-images.githubusercontent.com/5289274/77823341-62063200-7135-11ea-8139-eba393e069d5.png)

Is there a problem here in my settings? 

Thank you for any help,
Zimeng Wang

**Comment by srio** [comment]
Dear Zimeng,

everything depends on what you call source size. Your settings look correct.

What you get in the plot is the cartesian projection of the rays on the (x,z) plane. But this is not the size, as the effect of the depth is ignored. 

In order to get into account the depth you can propagate the source to a screen in the far field, and then backpropagate to the source plane again. Or, similarly the use of a sort of "ideal lens" or ideal mirror to make a 1 to 1 image. 
I prefer to "propagate" all the rays to the (x,z) plane (not project!) just by adding a PlotXY widget and retracing to a distance zero. This will calculate the intersection of every ray in the (x,z) plane and gives a better idea of the source size:

![image](https://user-images.githubusercontent.com/502315/79943017-b3e06600-841c-11ea-9620-2bce71c7d8fb.png)


You see that the image has a Lorentzian shape typical of a source with depth. Pay attention to the dimensions: FWHM is 934 x 83 um but the sigmas are: 1890 x 130 um. The vertical size depends much on the energy range.  For a Gaussian distribution FWHM=2.35 sigma, and here sigmas are higher than FWHM because of the long tails of the Lorentzian. 

I hope this helps!. 

Regards, Manuel

**Comment by zimeng657** [comment]
Dear  Manuel ，

Thank you very much! This really helps!

Best,
Zimeng

**Comment by srio** [comment]
You're welcomed!
