### ISSUE TITLE
Parabolic mirror with small distances

### ISSUE THREAD

**Issue by buddyguy59** [oasys-kit/shadow3#54]
Hello. 

Please help me with modeling the reflection from parabolic mirrors.
![image](https://user-images.githubusercontent.com/100803224/156448245-0a6a8297-e41a-4073-85cc-3526e95a4cb1.png)

I take geometrical source with wavelenght 1.54A  and try to focusing. 
![image](https://user-images.githubusercontent.com/100803224/156446939-0d167895-5da0-49f7-9c79-cb5dd674e2e8.png)
 
And i got good results for focusing by parabolic mirror with small distances. For example, source distance 14cm, Image 29 and paraboloid parameter 30 cm.
![image](https://user-images.githubusercontent.com/100803224/156447338-65fa84d1-d689-465d-8182-ac7a98c8b8ec.png)

Are these results correct ? Can I use small distances ?
[parabolic mirror.zip](https://github.com/oasys-kit/shadow3/files/8172888/parabolic.mirror.zip)

And how I can set roughnes if I only have image from atomic-force microscope with some data like RMS, without any special files ?
![image](https://user-images.githubusercontent.com/100803224/156448776-d200e38d-7961-4e4b-af70-f5301097d2e9.png)

**Comment by srio** [comment]
Hello, 
if you use a parabolic mirror is because you want a focus a collimated source. Therefore the source divergence must be zero (or close to zero). Then I suggest to select the automatic setting of the parabola parameters and you get a perfect focusing (as in  [parabolic mirror.ows.zip](https://github.com/oasys-kit/shadow3/files/8191147/parabolic.mirror.ows.zip) ).

If you want to use the roughness option (this option is not very used however) you need the RMS value (you have it) but also the spectral power density of the surface map. An old document with an example of this option is in https://github.com/srio/shadow3-docs/blob/master/doc/SHADOW_roughness.pdf

**Comment by srio** [comment]
I aides the roughness example workspace in https://github.com/oasys-kit/ShadowOui-Tutorial

you can import it in OASYS fro, the URL
https://raw.githubusercontent.com/oasys-kit/ShadowOui-Tutorial/master/OTHER_EXAMPLES/roughness_demo.ows
